//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/lib/pq"
)

type AtlasSchemaRevisions struct {
	Version         string `sql:"primary_key"`
	Description     string
	Type            int64
	Applied         int32
	Total           int32
	ExecutedAt      time.Time
	ExecutionTime   int64
	Error           string
	ErrorStmt       string
	Hash            string
	PartialHashes   pq.StringArray
	OperatorVersion string
}
