//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/lib/pq"
)

type AuthorizationCodes struct {
	ID                  []byte `sql:"primary_key"`
	CodeHash            []byte
	UserID              []byte
	ClientID            []byte
	RedirectURI         string
	Scopes              pq.StringArray
	CodeChallenge       string
	CodeChallengeMethod string
	Nonce               *string
	ExpiresAt           time.Time
	UsedAt              *time.Time
	CreatedAt           time.Time
}
