//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/lib/pq"
)

type Clients struct {
	ID            []byte `sql:"primary_key"`
	UserID        []byte
	Name          string
	RedirectURI   string
	AllowedScopes pq.StringArray
	RevokedAt     *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
