//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/lib/pq"
)

type UserClientAuthorizations struct {
	ID               []byte `sql:"primary_key"`
	UserID           []byte
	ClientID         []byte
	GrantedScopes    pq.StringArray
	LastAuthorizedAt time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
