//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuthorizationCodes = newAuthorizationCodesTable("public", "authorization_codes", "")

type authorizationCodesTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnBytea
	CodeHash            postgres.ColumnBytea
	UserID              postgres.ColumnBytea
	ClientID            postgres.ColumnBytea
	RedirectURI         postgres.ColumnString
	Scopes              postgres.ColumnStringArray
	CodeChallenge       postgres.ColumnString
	CodeChallengeMethod postgres.ColumnString
	Nonce               postgres.ColumnString
	ExpiresAt           postgres.ColumnTimestampz
	UsedAt              postgres.ColumnTimestampz
	CreatedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuthorizationCodesTable struct {
	authorizationCodesTable

	EXCLUDED authorizationCodesTable
}

// AS creates new AuthorizationCodesTable with assigned alias
func (a AuthorizationCodesTable) AS(alias string) *AuthorizationCodesTable {
	return newAuthorizationCodesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthorizationCodesTable with assigned schema name
func (a AuthorizationCodesTable) FromSchema(schemaName string) *AuthorizationCodesTable {
	return newAuthorizationCodesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthorizationCodesTable with assigned table prefix
func (a AuthorizationCodesTable) WithPrefix(prefix string) *AuthorizationCodesTable {
	return newAuthorizationCodesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthorizationCodesTable with assigned table suffix
func (a AuthorizationCodesTable) WithSuffix(suffix string) *AuthorizationCodesTable {
	return newAuthorizationCodesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthorizationCodesTable(schemaName, tableName, alias string) *AuthorizationCodesTable {
	return &AuthorizationCodesTable{
		authorizationCodesTable: newAuthorizationCodesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newAuthorizationCodesTableImpl("", "excluded", ""),
	}
}

func newAuthorizationCodesTableImpl(schemaName, tableName, alias string) authorizationCodesTable {
	var (
		IDColumn                  = postgres.ByteaColumn("id")
		CodeHashColumn            = postgres.ByteaColumn("code_hash")
		UserIDColumn              = postgres.ByteaColumn("user_id")
		ClientIDColumn            = postgres.ByteaColumn("client_id")
		RedirectURIColumn         = postgres.StringColumn("redirect_uri")
		ScopesColumn              = postgres.StringArrayColumn("scopes")
		CodeChallengeColumn       = postgres.StringColumn("code_challenge")
		CodeChallengeMethodColumn = postgres.StringColumn("code_challenge_method")
		NonceColumn               = postgres.StringColumn("nonce")
		ExpiresAtColumn           = postgres.TimestampzColumn("expires_at")
		UsedAtColumn              = postgres.TimestampzColumn("used_at")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		allColumns                = postgres.ColumnList{IDColumn, CodeHashColumn, UserIDColumn, ClientIDColumn, RedirectURIColumn, ScopesColumn, CodeChallengeColumn, CodeChallengeMethodColumn, NonceColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{CodeHashColumn, UserIDColumn, ClientIDColumn, RedirectURIColumn, ScopesColumn, CodeChallengeColumn, CodeChallengeMethodColumn, NonceColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn}
		defaultColumns            = postgres.ColumnList{CreatedAtColumn}
	)

	return authorizationCodesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		CodeHash:            CodeHashColumn,
		UserID:              UserIDColumn,
		ClientID:            ClientIDColumn,
		RedirectURI:         RedirectURIColumn,
		Scopes:              ScopesColumn,
		CodeChallenge:       CodeChallengeColumn,
		CodeChallengeMethod: CodeChallengeMethodColumn,
		Nonce:               NonceColumn,
		ExpiresAt:           ExpiresAtColumn,
		UsedAt:              UsedAtColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
