//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Clients = newClientsTable("public", "clients", "")

type clientsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnBytea
	UserID        postgres.ColumnBytea
	Name          postgres.ColumnString
	RedirectURI   postgres.ColumnString
	AllowedScopes postgres.ColumnStringArray
	RevokedAt     postgres.ColumnTimestampz
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ClientsTable struct {
	clientsTable

	EXCLUDED clientsTable
}

// AS creates new ClientsTable with assigned alias
func (a ClientsTable) AS(alias string) *ClientsTable {
	return newClientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ClientsTable with assigned schema name
func (a ClientsTable) FromSchema(schemaName string) *ClientsTable {
	return newClientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ClientsTable with assigned table prefix
func (a ClientsTable) WithPrefix(prefix string) *ClientsTable {
	return newClientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ClientsTable with assigned table suffix
func (a ClientsTable) WithSuffix(suffix string) *ClientsTable {
	return newClientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newClientsTable(schemaName, tableName, alias string) *ClientsTable {
	return &ClientsTable{
		clientsTable: newClientsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newClientsTableImpl("", "excluded", ""),
	}
}

func newClientsTableImpl(schemaName, tableName, alias string) clientsTable {
	var (
		IDColumn            = postgres.ByteaColumn("id")
		UserIDColumn        = postgres.ByteaColumn("user_id")
		NameColumn          = postgres.StringColumn("name")
		RedirectURIColumn   = postgres.StringColumn("redirect_uri")
		AllowedScopesColumn = postgres.StringArrayColumn("allowed_scopes")
		RevokedAtColumn     = postgres.TimestampzColumn("revoked_at")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, UserIDColumn, NameColumn, RedirectURIColumn, AllowedScopesColumn, RevokedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{UserIDColumn, NameColumn, RedirectURIColumn, AllowedScopesColumn, RevokedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return clientsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		UserID:        UserIDColumn,
		Name:          NameColumn,
		RedirectURI:   RedirectURIColumn,
		AllowedScopes: AllowedScopesColumn,
		RevokedAt:     RevokedAtColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
