//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailVerificationTokens = newEmailVerificationTokensTable("public", "email_verification_tokens", "")

type emailVerificationTokensTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnBytea
	UserID    postgres.ColumnBytea
	TokenHash postgres.ColumnBytea
	ExpiresAt postgres.ColumnTimestampz
	RevokedAt postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmailVerificationTokensTable struct {
	emailVerificationTokensTable

	EXCLUDED emailVerificationTokensTable
}

// AS creates new EmailVerificationTokensTable with assigned alias
func (a EmailVerificationTokensTable) AS(alias string) *EmailVerificationTokensTable {
	return newEmailVerificationTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailVerificationTokensTable with assigned schema name
func (a EmailVerificationTokensTable) FromSchema(schemaName string) *EmailVerificationTokensTable {
	return newEmailVerificationTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmailVerificationTokensTable with assigned table prefix
func (a EmailVerificationTokensTable) WithPrefix(prefix string) *EmailVerificationTokensTable {
	return newEmailVerificationTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmailVerificationTokensTable with assigned table suffix
func (a EmailVerificationTokensTable) WithSuffix(suffix string) *EmailVerificationTokensTable {
	return newEmailVerificationTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmailVerificationTokensTable(schemaName, tableName, alias string) *EmailVerificationTokensTable {
	return &EmailVerificationTokensTable{
		emailVerificationTokensTable: newEmailVerificationTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newEmailVerificationTokensTableImpl("", "excluded", ""),
	}
}

func newEmailVerificationTokensTableImpl(schemaName, tableName, alias string) emailVerificationTokensTable {
	var (
		IDColumn        = postgres.ByteaColumn("id")
		UserIDColumn    = postgres.ByteaColumn("user_id")
		TokenHashColumn = postgres.ByteaColumn("token_hash")
		ExpiresAtColumn = postgres.TimestampzColumn("expires_at")
		RevokedAtColumn = postgres.TimestampzColumn("revoked_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TokenHashColumn, ExpiresAtColumn, RevokedAtColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, TokenHashColumn, ExpiresAtColumn, RevokedAtColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return emailVerificationTokensTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		TokenHash: TokenHashColumn,
		ExpiresAt: ExpiresAtColumn,
		RevokedAt: RevokedAtColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
