//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PasswordResetTokens = newPasswordResetTokensTable("public", "password_reset_tokens", "")

type passwordResetTokensTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnBytea
	UserID    postgres.ColumnBytea
	TokenHash postgres.ColumnBytea
	ExpiresAt postgres.ColumnTimestampz
	RevokedAt postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PasswordResetTokensTable struct {
	passwordResetTokensTable

	EXCLUDED passwordResetTokensTable
}

// AS creates new PasswordResetTokensTable with assigned alias
func (a PasswordResetTokensTable) AS(alias string) *PasswordResetTokensTable {
	return newPasswordResetTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PasswordResetTokensTable with assigned schema name
func (a PasswordResetTokensTable) FromSchema(schemaName string) *PasswordResetTokensTable {
	return newPasswordResetTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PasswordResetTokensTable with assigned table prefix
func (a PasswordResetTokensTable) WithPrefix(prefix string) *PasswordResetTokensTable {
	return newPasswordResetTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PasswordResetTokensTable with assigned table suffix
func (a PasswordResetTokensTable) WithSuffix(suffix string) *PasswordResetTokensTable {
	return newPasswordResetTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPasswordResetTokensTable(schemaName, tableName, alias string) *PasswordResetTokensTable {
	return &PasswordResetTokensTable{
		passwordResetTokensTable: newPasswordResetTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newPasswordResetTokensTableImpl("", "excluded", ""),
	}
}

func newPasswordResetTokensTableImpl(schemaName, tableName, alias string) passwordResetTokensTable {
	var (
		IDColumn        = postgres.ByteaColumn("id")
		UserIDColumn    = postgres.ByteaColumn("user_id")
		TokenHashColumn = postgres.ByteaColumn("token_hash")
		ExpiresAtColumn = postgres.TimestampzColumn("expires_at")
		RevokedAtColumn = postgres.TimestampzColumn("revoked_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TokenHashColumn, ExpiresAtColumn, RevokedAtColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{IDColumn, UserIDColumn, TokenHashColumn, ExpiresAtColumn, RevokedAtColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return passwordResetTokensTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		TokenHash: TokenHashColumn,
		ExpiresAt: ExpiresAtColumn,
		RevokedAt: RevokedAtColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
