//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AuthorizationCodes = AuthorizationCodes.FromSchema(schema)
	Clients = Clients.FromSchema(schema)
	EmailVerificationTokens = EmailVerificationTokens.FromSchema(schema)
	Events = Events.FromSchema(schema)
	PasswordResetTokens = PasswordResetTokens.FromSchema(schema)
	RefreshTokens = RefreshTokens.FromSchema(schema)
	Roles = Roles.FromSchema(schema)
	UserClientAuthorizations = UserClientAuthorizations.FromSchema(schema)
	UserRoles = UserRoles.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
