//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserClientAuthorizations = newUserClientAuthorizationsTable("public", "user_client_authorizations", "")

type userClientAuthorizationsTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnBytea
	UserID           postgres.ColumnBytea
	ClientID         postgres.ColumnBytea
	GrantedScopes    postgres.ColumnStringArray
	LastAuthorizedAt postgres.ColumnTimestampz
	RevokedAt        postgres.ColumnTimestampz
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserClientAuthorizationsTable struct {
	userClientAuthorizationsTable

	EXCLUDED userClientAuthorizationsTable
}

// AS creates new UserClientAuthorizationsTable with assigned alias
func (a UserClientAuthorizationsTable) AS(alias string) *UserClientAuthorizationsTable {
	return newUserClientAuthorizationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserClientAuthorizationsTable with assigned schema name
func (a UserClientAuthorizationsTable) FromSchema(schemaName string) *UserClientAuthorizationsTable {
	return newUserClientAuthorizationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserClientAuthorizationsTable with assigned table prefix
func (a UserClientAuthorizationsTable) WithPrefix(prefix string) *UserClientAuthorizationsTable {
	return newUserClientAuthorizationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserClientAuthorizationsTable with assigned table suffix
func (a UserClientAuthorizationsTable) WithSuffix(suffix string) *UserClientAuthorizationsTable {
	return newUserClientAuthorizationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserClientAuthorizationsTable(schemaName, tableName, alias string) *UserClientAuthorizationsTable {
	return &UserClientAuthorizationsTable{
		userClientAuthorizationsTable: newUserClientAuthorizationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newUserClientAuthorizationsTableImpl("", "excluded", ""),
	}
}

func newUserClientAuthorizationsTableImpl(schemaName, tableName, alias string) userClientAuthorizationsTable {
	var (
		IDColumn               = postgres.ByteaColumn("id")
		UserIDColumn           = postgres.ByteaColumn("user_id")
		ClientIDColumn         = postgres.ByteaColumn("client_id")
		GrantedScopesColumn    = postgres.StringArrayColumn("granted_scopes")
		LastAuthorizedAtColumn = postgres.TimestampzColumn("last_authorized_at")
		RevokedAtColumn        = postgres.TimestampzColumn("revoked_at")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		allColumns             = postgres.ColumnList{IDColumn, UserIDColumn, ClientIDColumn, GrantedScopesColumn, LastAuthorizedAtColumn, RevokedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = postgres.ColumnList{UserIDColumn, ClientIDColumn, GrantedScopesColumn, LastAuthorizedAtColumn, RevokedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns         = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return userClientAuthorizationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		UserID:           UserIDColumn,
		ClientID:         ClientIDColumn,
		GrantedScopes:    GrantedScopesColumn,
		LastAuthorizedAt: LastAuthorizedAtColumn,
		RevokedAt:        RevokedAtColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
