//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RefreshTokens struct {
	ID        []byte `sql:"primary_key"`
	UserID    []byte
	ParentID  *[]byte
	IssuedAt  time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
	IPAddress string
	UserAgent string
}
